---
sudo: required
dist: trusty

language: python
python: "2.7"

branches:
  only:
    - ansible-3

before_install:
  - sudo apt-get update -qq
  - sudo rm -vf /etc/apt/sources.list.d/*riak*

install:
  - sudo apt-get install -y unzip wget
  - wget -O packer.zip https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
  - mkdir -p /home/travis/bin
  - sudo unzip packer.zip -d /home/travis/bin
  - wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.2/terraform_0.11.2_linux_amd64.zip
  - sudo unzip terraform.zip -d /home/travis/bin
  - wget -O tflint.zip https://github.com/wata727/tflint/releases/download/v0.5.4/tflint_linux_amd64.zip
  - sudo unzip tflint.zip -d /home/travis/bin
  - pip install ansible
  - pip install ansible-lint

before_script:
  - /home/travis/bin/packer --version
  - WD=$(pwd)
  - touch ~/.ssh/appuser.pub && touch ~/.ssh/appuser
  - cd ${WD}/terraform/stage
  - |
    cat > ./terraform.tfvars << '  EOF'
    project = "infra-188820"
    public_key_path = "~/.ssh/appuser.pub"
    private_key_path = "~/.ssh/appuser"
    disk_image = "reddit-base"
    EOF
  - cat ./terraform.tfvars
  - cp ./terraform.tfvars ../prod/

script:
  - cd ${WD}
  - /home/travis/bin/packer validate --var-file=packer/variables.json.example packer/db.json
  - cd ${WD}/ansible
  - test -f playbooks/site.yml
  - ansible-lint playbooks/site.yml
  - cd ${WD}/terraform/stage
  - terraform init
  - terraform validate
  - tflint --error-with-issues
  - cd ${WD}/terraform/prod
  - terraform init
  - terraform validate
  - tflint --error-with-issues 
